name: Feature request
description: Suggest an improvement for ServerAdmin
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: need
    attributes:
      label: Problem or need
      description: What task should become easier?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
